import { NameOfAllah, LevelConfig, DifficultyLevel } from './types';

export const DifficultyConfig: Record<DifficultyLevel, LevelConfig> = {
  easy: { questions: 10, timeLimit: 300 }, // 5 minutes
  medium: { questions: 33, timeLimit: 900 }, // 15 minutes
  hard: { questions: 99, timeLimit: 2700 } // 45 minutes
};

export const NAMES_OF_ALLAH: NameOfAllah[] = [
  { id: 1, arabic: "الرَّحْمَنُ", transliteration: "Ar-Rahman", meaning: "The Most Gracious", bn: { transliteration: "আর-রাহমান", meaning: "পরম দয়ালু" } },
  { id: 2, arabic: "الرَّحِيمُ", transliteration: "Ar-Rahim", meaning: "The Most Merciful", bn: { transliteration: "আর-রাহীম", meaning: "পরম করুণাময়" } },
  { id: 3, arabic: "الْمَلِكُ", transliteration: "Al-Malik", meaning: "The Sovereign", bn: { transliteration: "আল-মালিক", meaning: "সর্বাধিপতি" } },
  { id: 4, arabic: "الْقُدُّوسُ", transliteration: "Al-Quddus", meaning: "The Most Holy", bn: { transliteration: "আল-কুদ্দুস", meaning: "নিষ্কলুষ" } },
  { id: 5, arabic: "السَّلاَمُ", transliteration: "As-Salam", meaning: "The Source of Peace", bn: { transliteration: "আস-সালাম", meaning: "শান্তি দানকারী" } },
  { id: 6, arabic: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: "The Giver of Faith", bn: { transliteration: "আল-মুমিন", meaning: "নিরাপত্তা দানকারী" } },
  { id: 7, arabic: "الْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "The Guardian", bn: { transliteration: "আল-মুহাইমিন", meaning: "রক্ষনাবেক্ষণকারী" } },
  { id: 8, arabic: "الْعَزِيزُ", transliteration: "Al-Aziz", meaning: "The Almighty", bn: { transliteration: "আল-আজিজ", meaning: "পরাক্রমশালী" } },
  { id: 9, arabic: "الْجَبَّارُ", transliteration: "Al-Jabbar", meaning: "The Compeller", bn: { transliteration: "আল-জাব্বার", meaning: "মহাপ্রতাপশালী" } },
  { id: 10, arabic: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "The Majestic", bn: { transliteration: "আল-মুতাকাব্বির", meaning: "মহিমান্বিত" } },
  { id: 11, arabic: "الْخَالِقُ", transliteration: "Al-Khaliq", meaning: "The Creator", bn: { transliteration: "আল-খালিক", meaning: "সৃজনকারী" } },
  { id: 12, arabic: "الْبَارِئُ", transliteration: "Al-Bari'", meaning: "The Maker of Order", bn: { transliteration: "আল-বারী", meaning: "সঠিকভাবে সৃষ্টিকারী" } },
  { id: 13, arabic: "الْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning: "The Fashioner", bn: { transliteration: "আল-মুসাব্বির", meaning: "রূপদানকারী" } },
  { id: 14, arabic: "الْغَفَّارُ", transliteration: "Al-Ghaffar", meaning: "The Great Forgiver", bn: { transliteration: "আল-গাফফার", meaning: "মহাক্ষমাশীল" } },
  { id: 15, arabic: "الْقَهَّارُ", transliteration: "Al-Qahhar", meaning: "The Subduer", bn: { transliteration: "আল-কাহহার", meaning: "মহাপরাক্রমশালী" } },
  { id: 16, arabic: "الْوَهَّابُ", transliteration: "Al-Wahhab", meaning: "The Giver of All", bn: { transliteration: "আল-ওয়াহহাব", meaning: "মহা দাতা" } },
  { id: 17, arabic: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "The Provider", bn: { transliteration: "আর-রাজ্জাক", meaning: "রিজিকদাতা" } },
  { id: 18, arabic: "الْفَتَّاحُ", transliteration: "Al-Fattah", meaning: "The Opener", bn: { transliteration: "আল-ফাত্তাহ", meaning: "বিজয়দানকারী" } },
  { id: 19, arabic: "الْعَلِيمُ", transliteration: "Al-'Alim", meaning: "The All-Knowing", bn: { transliteration: "আল-আলিম", meaning: "মহাজ্ঞানী" } },
  { id: 20, arabic: "الْقَابِضُ", transliteration: "Al-Qabid", meaning: "The Constrictor", bn: { transliteration: "আল-কাবিদ", meaning: "সংকুচিতকারী" } },
  { id: 21, arabic: "الْبَاسِطُ", transliteration: "Al-Basit", meaning: "The Expander", bn: { transliteration: "আল-বাসিত", meaning: "প্রশস্তকারী" } },
  { id: 22, arabic: "الْخَافِضُ", transliteration: "Al-Khafid", meaning: "The Abaser", bn: { transliteration: "আল-খাফিদ", meaning: "অবনতকারী" } },
  { id: 23, arabic: "الرَّافِعُ", transliteration: "Ar-Rafi", meaning: "The Exalter", bn: { transliteration: "আর-রাফি", meaning: "উন্নতকারী" } },
  { id: 24, arabic: "الْمُعِزُّ", transliteration: "Al-Mu'izz", meaning: "The Bestower of Honor", bn: { transliteration: "আল-মুইজ্জ", meaning: "সম্মানদানকারী" } },
  { id: 25, arabic: "الْمُذِلُّ", transliteration: "Al-Mudhill", meaning: "The Humiliator", bn: { transliteration: "আল-মুজিল্ল", meaning: "লঞ্ছনাকারী" } },
  { id: 26, arabic: "السَّمِيعُ", transliteration: "As-Sami", meaning: "The All-Hearing", bn: { transliteration: "আস-সামি", meaning: "সর্বশ্রোতা" } },
  { id: 27, arabic: "الْبَصِيرُ", transliteration: "Al-Basir", meaning: "The All-Seeing", bn: { transliteration: "আল-বাসির", meaning: "সর্বদ্রষ্টা" } },
  { id: 28, arabic: "الْحَكَمُ", transliteration: "Al-Hakam", meaning: "The Judge", bn: { transliteration: "আল-হাকাম", meaning: "বিচারক" } },
  { id: 29, arabic: "الْعَدْلُ", transliteration: "Al-'Adl", meaning: "The Just", bn: { transliteration: "আল-আদল", meaning: "ন্যায়বিচারক" } },
  { id: 30, arabic: "اللَّطِيفُ", transliteration: "Al-Latif", meaning: "The Subtle One", bn: { transliteration: "আল-লাতিফ", meaning: "সূক্ষ্মদর্শী" } },
  { id: 31, arabic: "الْخَبِيرُ", transliteration: "Al-Khabir", meaning: "The All-Aware", bn: { transliteration: "আল-খাবির", meaning: "মহা সংবাদরক্ষক" } },
  { id: 32, arabic: "الْحَلِيمُ", transliteration: "Al-Halim", meaning: "The Forbearing", bn: { transliteration: "আল-হালিম", meaning: "মহাসহিষ্ণু" } },
  { id: 33, arabic: "الْعَظِيمُ", transliteration: "Al-Azim", meaning: "The Magnificent", bn: { transliteration: "আল-আজিম", meaning: "মহান" } },
  { id: 34, arabic: "الْغَفُورُ", transliteration: "Al-Ghafur", meaning: "The All-Forgiving", bn: { transliteration: "আল-গফুর", meaning: "ক্ষমাশীল" } },
  { id: 35, arabic: "الشَّكُورُ", transliteration: "Ash-Shakur", meaning: "The Appreciative", bn: { transliteration: "আশ-শাকুর", meaning: "গুণগ্রাহী" } },
  { id: 36, arabic: "الْعَلِيُّ", transliteration: "Al-'Ali", meaning: "The Highest", bn: { transliteration: "আল-আলী", meaning: "উচ্চ মর্যাদাবান" } },
  { id: 37, arabic: "الْكَبِيرُ", transliteration: "Al-Kabir", meaning: "The Greatest", bn: { transliteration: "আল-কাবির", meaning: "সুমহান" } },
  { id: 38, arabic: "الْحَفِيظُ", transliteration: "Al-Hafiz", meaning: "The Preserver", bn: { transliteration: "আল-হাফিজ", meaning: "সংরক্ষণকারী" } },
  { id: 39, arabic: "الْمُقِيتُ", transliteration: "Al-Muqit", meaning: "The Nourisher", bn: { transliteration: "আল-মুকিত", meaning: "আহারদাতা" } },
  { id: 40, arabic: "الْحَسِيبُ", transliteration: "Al-Hasib", meaning: "The Reckoner", bn: { transliteration: "আল-হাসিব", meaning: "হিসাব গ্রহণকারী" } },
  { id: 41, arabic: "الْجَلِيلُ", transliteration: "Al-Jalil", meaning: "The Majestic", bn: { transliteration: "আল-জলিল", meaning: "মহিমাম্বিত" } },
  { id: 42, arabic: "الْكَرِيمُ", transliteration: "Al-Karim", meaning: "The Generous", bn: { transliteration: "আল-কারিম", meaning: "মহামহিম" } },
  { id: 43, arabic: "الرَّقِيبُ", transliteration: "Ar-Raqib", meaning: "The Watchful", bn: { transliteration: "আর-রাকিব", meaning: "তত্ত্বাবধায়ক" } },
  { id: 44, arabic: "الْمُجِيبُ", transliteration: "Al-Mujib", meaning: "The Responsive", bn: { transliteration: "আল-মুজিব", meaning: "সাড়া দানকারী" } },
  { id: 45, arabic: "الْوَاسِعُ", transliteration: "Al-Wasi", meaning: "The All-Pervading", bn: { transliteration: "আল-ওয়াসি", meaning: "অসীম" } },
  { id: 46, arabic: "الْحَكِيمُ", transliteration: "Al-Hakim", meaning: "The Wise", bn: { transliteration: "আল-হাকিম", meaning: "প্রজ্ঞাময়" } },
  { id: 47, arabic: "الْوَدُودُ", transliteration: "Al-Wadud", meaning: "The Loving", bn: { transliteration: "আল-ওয়াদুদ", meaning: "প্রেমময়" } },
  { id: 48, arabic: "الْمَجِيدُ", transliteration: "Al-Majid", meaning: "The Most Glorious", bn: { transliteration: "আল-মাজিদ", meaning: "মর্যাদাবান" } },
  { id: 49, arabic: "الْبَاعِثُ", transliteration: "Al-Ba'ith", meaning: "The Resurrector", bn: { transliteration: "আল-বাইছ", meaning: "পুনরুজ্জীবিতকারী" } },
  { id: 50, arabic: "الشَّهِيدُ", transliteration: "Ash-Shahid", meaning: "The Witness", bn: { transliteration: "আশ-শহীদ", meaning: "সাক্ষী" } },
  { id: 51, arabic: "الْحَقُّ", transliteration: "Al-Haqq", meaning: "The Truth", bn: { transliteration: "আল-হক", meaning: "সত্য" } },
  { id: 52, arabic: "الْوَكِيلُ", transliteration: "Al-Wakil", meaning: "The Trustee", bn: { transliteration: "আল-ওয়াকিল", meaning: "কার্যনির্বাহক" } },
  { id: 53, arabic: "الْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: "The Strong", bn: { transliteration: "আল-কাউয়ী", meaning: "শক্তিশালী" } },
  { id: 54, arabic: "الْمَتِينُ", transliteration: "Al-Matin", meaning: "The Firm", bn: { transliteration: "আল-মতিন", meaning: "সুদৃঢ়" } },
  { id: 55, arabic: "الْوَلِيُّ", transliteration: "Al-Waliyy", meaning: "The Patron", bn: { transliteration: "আল-ওয়ালি", meaning: "অভিভাবক" } },
  { id: 56, arabic: "الْحَمِيدُ", transliteration: "Al-Hamid", meaning: "The Praiseworthy", bn: { transliteration: "আল-হামিদ", meaning: "প্রশংসিত" } },
  { id: 57, arabic: "الْمُحْصِي", transliteration: "Al-Muhsi", meaning: "The Accounter", bn: { transliteration: "আল-মুহসি", meaning: "হিসাব রক্ষাকারী" } },
  { id: 58, arabic: "الْمُبْدِئُ", transliteration: "Al-Mubdi", meaning: "The Originator", bn: { transliteration: "আল-মুবদি", meaning: "প্রথম সৃজনকারী" } },
  { id: 59, arabic: "الْمُعِيدُ", transliteration: "Al-Mu'id", meaning: "The Restorer", bn: { transliteration: "আল-মুঈদ", meaning: "পুনঃসৃজনকারী" } },
  { id: 60, arabic: "الْمُحْيِي", transliteration: "Al-Muhyi", meaning: "The Giver of Life", bn: { transliteration: "আল-মুহাইয়ি", meaning: "জীবনদানকারী" } },
  { id: 61, arabic: "الْمُمِيتُ", transliteration: "Al-Mumit", meaning: "The Giver of Death", bn: { transliteration: "আল-মুমিত", meaning: "মৃত্যুদাতা" } },
  { id: 62, arabic: "الْحَيُّ", transliteration: "Al-Hayy", meaning: "The Ever-Living", bn: { transliteration: "আল-হাইয়্যু", meaning: "চিরঞ্জীব" } },
  { id: 63, arabic: "الْقَيُّومُ", transliteration: "Al-Qayyum", meaning: "The Self-Sustaining", bn: { transliteration: "আল-কাইয়ুম", meaning: "চিরস্থায়ী" } },
  { id: 64, arabic: "الْوَاجِدُ", transliteration: "Al-Wajid", meaning: "The Perceiver", bn: { transliteration: "আল-ওয়াজিদ", meaning: "অস্তিত্বদানকারী" } },
  { id: 65, arabic: "الْمَاجِدُ", transliteration: "Al-Majid", meaning: "The Illustrious", bn: { transliteration: "আল-মাজিদ", meaning: "মর্যাদাবান" } },
  { id: 66, arabic: "الْواحِدُ", transliteration: "Al-Wahid", meaning: "The One", bn: { transliteration: "আল-ওয়াহিদ", meaning: "একক সত্তা" } },
  { id: 67, arabic: "الْاَحَدُ", transliteration: "Al-Ahad", meaning: "The Only One", bn: { transliteration: "আল-আহাদ", meaning: "এক" } },
  { id: 68, arabic: "الصَّمَدُ", transliteration: "As-Samad", meaning: "The Self-Sufficient", bn: { transliteration: "আস-সামাদ", meaning: "অমুখাপেক্ষী" } },
  { id: 69, arabic: "الْقَادِرُ", transliteration: "Al-Qadir", meaning: "The Capable", bn: { transliteration: "আল-কadir", meaning: "সর্বশক্তিমান" } },
  { id: 70, arabic: "الْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "The Omnipotent", bn: { transliteration: "আল-মুকতাদির", meaning: "ক্ষমতাবান" } },
  { id: 71, arabic: "الْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "The Expediter", bn: { transliteration: "আল-মুকাদ্দিম", meaning: "অগ্রসরকারী" } },
  { id: 72, arabic: "الْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer", bn: { transliteration: "আল-মুয়াক্ষির", meaning: "পশ্চাদপদকারী" } },
  { id: 73, arabic: "الأَوَّلُ", transliteration: "Al-Awwal", meaning: "The First", bn: { transliteration: "আল-আউয়াল", meaning: "আনাদি" } },
  { id: 74, arabic: "الآخِرُ", transliteration: "Al-Akhir", meaning: "The Last", bn: { transliteration: "আল-আখির", meaning: "অনন্ত" } },
  { id: 75, arabic: "الظَّاهِرُ", transliteration: "Az-Zahir", meaning: "The Manifest", bn: { transliteration: "আজ-জহির", meaning: "প্রকাশ্য" } },
  { id: 76, arabic: "الْبَاطِنُ", transliteration: "Al-Batin", meaning: "The Hidden", bn: { transliteration: "আল-বাতিন", meaning: "গোপন" } },
  { id: 77, arabic: "الْوَالِي", transliteration: "Al-Wali", meaning: "The Governor", bn: { transliteration: "আল-ওয়ালী", meaning: "অভিভাবক" } },
  { id: 78, arabic: "الْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning: "The Self-Exalted", bn: { transliteration: "আল-মুতাআলী", meaning: "সর্বোচ্চ" } },
  { id: 79, arabic: "الْبَرُّ", transliteration: "Al-Barr", meaning: "The Source of Goodness", bn: { transliteration: "আল-বার্", meaning: "কল্যাণদাতা" } },
  { id: 80, arabic: "التَّوَّابُ", transliteration: "At-Tawwab", meaning: "The Acceptor of Repentance", bn: { transliteration: "আত-তাওয়াব", meaning: "তওবা কবুলকারী" } },
  { id: 81, arabic: "الْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: "The Avenger", bn: { transliteration: "আল-মুনতাকিম", meaning: "প্রতিশোধ গ্রহণকারী" } },
  { id: 82, arabic: "العَفُوُّ", transliteration: "Al-'Afuww", meaning: "The Pardoner", bn: { transliteration: "আল-আফুউ", meaning: "ক্ষমাশীল" } },
  { id: 83, arabic: "الرَّؤُوفُ", transliteration: "Ar-Ra'uf", meaning: "The Most Kind", bn: { transliteration: "আর-রউফ", meaning: "স্নেহশীল" } },
  { id: 84, arabic: "مَالِكُ الْمُلْكِ", transliteration: "Malik-al-Mulk", meaning: "The Owner of All Sovereignty", bn: { transliteration: "মালিকুল মুলক", meaning: "সার্বভৌম ক্ষমতার মালিক" } },
  { id: 85, arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ", transliteration: "Dhu-al-Jalal wa-al-Ikram", meaning: "Lord of Majesty and Generosity", bn: { transliteration: "জুল জালালি ওয়াল ইকরাম", meaning: "মহিমান্বিত ও দয়াবান সত্তা" } },
  { id: 86, arabic: "الْمُقْسِطُ", transliteration: "Al-Muqsit", meaning: "The Equitable", bn: { transliteration: "আল-মুকসিত", meaning: "ন্যায়পরায়ণ" } },
  { id: 87, arabic: "الْجَامِعُ", transliteration: "Al-Jami", meaning: "The Gatherer", bn: { transliteration: "আল-জামি", meaning: "একত্রকারী" } },
  { id: 88, arabic: "الْغَنِيُّ", transliteration: "Al-Ghaniyy", meaning: "The Self-Sufficient", bn: { transliteration: "আল-গনি", meaning: "অভাবমুক্ত" } },
  { id: 89, arabic: "الْمُغْنِي", transliteration: "Al-Mughni", meaning: "The Enricher", bn: { transliteration: "আল-মুগনি", meaning: "প্রাচুর্য দানকারী" } },
  { id: 90, arabic: "الْمَانِعُ", transliteration: "Al-Mani'", meaning: "The Withholder", bn: { transliteration: "আল-মানি", meaning: "প্রতিরোধকারী" } },
  { id: 91, arabic: "الضَّارُّ", transliteration: "Ad-Darr", meaning: "The Creator of Harm", bn: { transliteration: "আদ-দার", meaning: "ক্ষতি করার ক্ষমতাসম্পন্ন" } },
  { id: 92, arabic: "النَّافِعُ", transliteration: "An-Nafi", meaning: "The Creator of Good", bn: { transliteration: "আন-নাফি", meaning: "উপকারকারী" } },
  { id: 93, arabic: "النُّورُ", transliteration: "An-Nur", meaning: "The Light", bn: { transliteration: "আন-নূর", meaning: "জ্যোতি" } },
  { id: 94, arabic: "الْهَادِي", transliteration: "Al-Hadi", meaning: "The Guide", bn: { transliteration: "আল-হাদী", meaning: "পথপ্রদর্শক" } },
  { id: 95, arabic: "الْبَدِيعُ", transliteration: "Al-Badi", meaning: "The Incomparable", bn: { transliteration: "আল-বাদী", meaning: "অতুলনীয় সৃজনকারী" } },
  { id: 96, arabic: "الْبَاقِي", transliteration: "Al-Baqi", meaning: "The Everlasting", bn: { transliteration: "আল-বাকী", meaning: "চিরস্থায়ী" } },
  { id: 97, arabic: "الْوَارِثُ", transliteration: "Al-Warith", meaning: "The Ultimate Inheritor", bn: { transliteration: "আল-ওয়ারিস", meaning: "উত্তরাধিকারী" } },
  { id: 98, arabic: "الرَّشِيدُ", transliteration: "Ar-Rashid", meaning: "The Guide to the Right Path", bn: { transliteration: "আর-রশিদ", meaning: "সঠিক পথপ্রদর্শক" } },
  { id: 99, arabic: "الصَّبُورُ", transliteration: "As-Sabur", meaning: "The Patient", bn: { transliteration: "আস-সবুর", meaning: "ধৈর্যশীল" } }
];