import { NameOfAllah, LevelConfig, DifficultyLevel } from './types';

export const DifficultyConfig: Record<DifficultyLevel, LevelConfig> = {
  easy: { questions: 10, timeLimit: null },
  medium: { questions: 33, timeLimit: 900 }, // 15 minutes
  hard: { questions: 99, timeLimit: 2700 } // 45 minutes
};

export const NAMES_OF_ALLAH: NameOfAllah[] = [
  { id: 1, arabic: "الرَّحْمَنُ", transliteration: "Ar-Rahman", meaning: "The Beneficent" },
  { id: 2, arabic: "الرَّحِيمُ", transliteration: "Ar-Rahim", meaning: "The Merciful" },
  { id: 3, arabic: "الْمَلِكُ", transliteration: "Al-Malik", meaning: "The King / Eternal Lord" },
  { id: 4, arabic: "الْقُدُّوسُ", transliteration: "Al-Quddus", meaning: "The Pure / The Holy" },
  { id: 5, arabic: "السَّلاَمُ", transliteration: "As-Salam", meaning: "The Source of Peace" },
  { id: 6, arabic: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: "The Inspirer of Faith" },
  { id: 7, arabic: "الْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "The Guardian" },
  { id: 8, arabic: "الْعَزِيزُ", transliteration: "Al-Aziz", meaning: "The Mighty / The Victorious" },
  { id: 9, arabic: "الْجَبَّارُ", transliteration: "Al-Jabbar", meaning: "The Compeller" },
  { id: 10, arabic: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "The Supreme / The Majestic" },
  { id: 11, arabic: "الْخَالِقُ", transliteration: "Al-Khaliq", meaning: "The Creator" },
  { id: 12, arabic: "الْبَارِئُ", transliteration: "Al-Bari'", meaning: "The Maker of Order" },
  { id: 13, arabic: "الْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning: "The Fashioner of Shapes" },
  { id: 14, arabic: "الْغَفَّارُ", transliteration: "Al-Ghaffar", meaning: "The Forgiving" },
  { id: 15, arabic: "الْقَهَّارُ", transliteration: "Al-Qahhar", meaning: "The Subduer" },
  { id: 16, arabic: "الْوَهَّابُ", transliteration: "Al-Wahhab", meaning: "The Giver of All" },
  { id: 17, arabic: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "The Sustainer" },
  { id: 18, arabic: "الْفَتَّاحُ", transliteration: "Al-Fattah", meaning: "The Opener" },
  { id: 19, arabic: "الْعَلِيمُ", transliteration: "Al-'Alim", meaning: "The All-Knowing" },
  { id: 20, arabic: "الْقَابِضُ", transliteration: "Al-Qabid", meaning: "The Constrictor" },
  { id: 21, arabic: "الْبَاسِطُ", transliteration: "Al-Basit", meaning: "The Expander" },
  { id: 22, arabic: "الْخَافِضُ", transliteration: "Al-Khafid", meaning: "The Abaser" },
  { id: 23, arabic: "الرَّافِعُ", transliteration: "Ar-Rafi", meaning: "The Exalter" },
  { id: 24, arabic: "الْمُعِزُّ", transliteration: "Al-Mu'izz", meaning: "The Bestower of Honors" },
  { id: 25, arabic: "الْمُذِلُّ", transliteration: "Al-Mudhill", meaning: "The Humiliator" },
  { id: 26, arabic: "السَّمِيعُ", transliteration: "As-Sami", meaning: "The All-Hearing" },
  { id: 27, arabic: "الْبَصِيرُ", transliteration: "Al-Basir", meaning: "The All-Seeing" },
  { id: 28, arabic: "الْحَكَمُ", transliteration: "Al-Hakam", meaning: "The Judge" },
  { id: 29, arabic: "الْعَدْلُ", transliteration: "Al-'Adl", meaning: "The Just" },
  { id: 30, arabic: "اللَّطِيفُ", transliteration: "Al-Latif", meaning: "The Subtle One" },
  { id: 31, arabic: "الْخَبِيرُ", transliteration: "Al-Khabir", meaning: "The All-Aware" },
  { id: 32, arabic: "الْحَلِيمُ", transliteration: "Al-Halim", meaning: "The Forbearing" },
  { id: 33, arabic: "الْعَظِيمُ", transliteration: "Al-Azim", meaning: "The Magnificent" },
  { id: 34, arabic: "الْغَفُورُ", transliteration: "Al-Ghafur", meaning: "The Forgiver and Hider of Faults" },
  { id: 35, arabic: "الشَّكُورُ", transliteration: "Ash-Shakur", meaning: "The Rewarder of Thankfulness" },
  { id: 36, arabic: "الْعَلِيُّ", transliteration: "Al-'Ali", meaning: "The Highest" },
  { id: 37, arabic: "الْكَبِيرُ", transliteration: "Al-Kabir", meaning: "The Greatest" },
  { id: 38, arabic: "الْحَفِيظُ", transliteration: "Al-Hafiz", meaning: "The Preserver" },
  { id: 39, arabic: "الْمُقِيتُ", transliteration: "Al-Muqit", meaning: "The Nourisher" },
  { id: 40, arabic: "الْحَسِيبُ", transliteration: "Al-Hasib", meaning: "The Accounter" },
  { id: 41, arabic: "الْجَلِيلُ", transliteration: "Al-Jalil", meaning: "The Mighty" },
  { id: 42, arabic: "الْكَرِيمُ", transliteration: "Al-Karim", meaning: "The Generous" },
  { id: 43, arabic: "الرَّقِيبُ", transliteration: "Ar-Raqib", meaning: "The Watchful One" },
  { id: 44, arabic: "الْمُجِيبُ", transliteration: "Al-Mujib", meaning: "The Responder to Prayer" },
  { id: 45, arabic: "الْوَاسِعُ", transliteration: "Al-Wasi", meaning: "The All-Encompassing" },
  { id: 46, arabic: "الْحَكِيمُ", transliteration: "Al-Hakim", meaning: "The Perfectly Wise" },
  { id: 47, arabic: "الْوَدُودُ", transliteration: "Al-Wadud", meaning: "The Loving One" },
  { id: 48, arabic: "الْمَجِيدُ", transliteration: "Al-Majid", meaning: "The Glorious One" },
  { id: 49, arabic: "الْبَاعِثُ", transliteration: "Al-Ba'ith", meaning: "The Resurrecter" },
  { id: 50, arabic: "الشَّهِيدُ", transliteration: "Ash-Shahid", meaning: "The Witness" },
  { id: 51, arabic: "الْحَقُّ", transliteration: "Al-Haqq", meaning: "The Truth" },
  { id: 52, arabic: "الْوَكِيلُ", transliteration: "Al-Wakil", meaning: "The Trustee" },
  { id: 53, arabic: "الْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: "The Possessor of All Strength" },
  { id: 54, arabic: "الْمَتِينُ", transliteration: "Al-Matin", meaning: "The Firm One" },
  { id: 55, arabic: "الْوَلِيُّ", transliteration: "Al-Waliyy", meaning: "The Protecting Friend" },
  { id: 56, arabic: "الْحَمِيدُ", transliteration: "Al-Hamid", meaning: "The Praised One" },
  { id: 57, arabic: "الْمُحْصِي", transliteration: "Al-Muhsi", meaning: "The Appraiser" },
  { id: 58, arabic: "الْمُبْدِئُ", transliteration: "Al-Mubdi", meaning: "The Originator" },
  { id: 59, arabic: "الْمُعِيدُ", transliteration: "Al-Mu'id", meaning: "The Restorer" },
  { id: 60, arabic: "الْمُحْيِي", transliteration: "Al-Muhyi", meaning: "The Giver of Life" },
  { id: 61, arabic: "الْمُمِيتُ", transliteration: "Al-Mumit", meaning: "The Taker of Life" },
  { id: 62, arabic: "الْحَيُّ", transliteration: "Al-Hayy", meaning: "The Ever Living One" },
  { id: 63, arabic: "الْقَيُّومُ", transliteration: "Al-Qayyum", meaning: "The Self-Existing One" },
  { id: 64, arabic: "الْوَاجِدُ", transliteration: "Al-Wajid", meaning: "The Finder" },
  { id: 65, arabic: "الْمَاجِدُ", transliteration: "Al-Majid", meaning: "The Noble" },
  { id: 66, arabic: "الْواحِدُ", transliteration: "Al-Wahid", meaning: "The Unique" },
  { id: 67, arabic: "الْاَحَدُ", transliteration: "Al-Ahad", meaning: "The One" },
  { id: 68, arabic: "الصَّمَدُ", transliteration: "As-Samad", meaning: "The Eternal" },
  { id: 69, arabic: "الْقَادِرُ", transliteration: "Al-Qadir", meaning: "The All-Powerful" },
  { id: 70, arabic: "الْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "The Determiner" },
  { id: 71, arabic: "الْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "The Expediter" },
  { id: 72, arabic: "الْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer" },
  { id: 73, arabic: "الأَوَّلُ", transliteration: "Al-Awwal", meaning: "The First" },
  { id: 74, arabic: "الآخِرُ", transliteration: "Al-Akhir", meaning: "The Last" },
  { id: 75, arabic: "الظَّاهِرُ", transliteration: "Az-Zahir", meaning: "The Manifest" },
  { id: 76, arabic: "الْبَاطِنُ", transliteration: "Al-Batin", meaning: "The Hidden" },
  { id: 77, arabic: "الْوَالِي", transliteration: "Al-Wali", meaning: "The Governor" },
  { id: 78, arabic: "الْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning: "The Supreme One" },
  { id: 79, arabic: "الْبَرُّ", transliteration: "Al-Barr", meaning: "The Doer of Good" },
  { id: 80, arabic: "التَّوَّابُ", transliteration: "At-Tawwab", meaning: "The Guide to Repentance" },
  { id: 81, arabic: "الْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: "The Avenger" },
  { id: 82, arabic: "العَفُوُّ", transliteration: "Al-'Afuww", meaning: "The Forgiver" },
  { id: 83, arabic: "الرَّؤُوفُ", transliteration: "Ar-Ra'uf", meaning: "The Clement" },
  { id: 84, arabic: "مَالِكُ الْمُلْكِ", transliteration: "Malik-al-Mulk", meaning: "The Owner of All" },
  { id: 85, arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ", transliteration: "Dhu-al-Jalal wa-al-Ikram", meaning: "The Lord of Majesty and Bounty" },
  { id: 86, arabic: "الْمُقْسِطُ", transliteration: "Al-Muqsit", meaning: "The Equitable" },
  { id: 87, arabic: "الْجَامِعُ", transliteration: "Al-Jami", meaning: "The Gatherer" },
  { id: 88, arabic: "الْغَنِيُّ", transliteration: "Al-Ghaniyy", meaning: "The Rich One" },
  { id: 89, arabic: "الْمُغْنِي", transliteration: "Al-Mughni", meaning: "The Enricher" },
  { id: 90, arabic: "الْمَانِعُ", transliteration: "Al-Mani'", meaning: "The Preventer of Harm" },
  { id: 91, arabic: "الضَّارُّ", transliteration: "Ad-Darr", meaning: "The Creator of The Harmful" },
  { id: 92, arabic: "النَّافِعُ", transliteration: "An-Nafi", meaning: "The Creator of Good" },
  { id: 93, arabic: "النُّورُ", transliteration: "An-Nur", meaning: "The Light" },
  { id: 94, arabic: "الْهَادِي", transliteration: "Al-Hadi", meaning: "The Guide" },
  { id: 95, arabic: "الْبَدِيعُ", transliteration: "Al-Badi", meaning: "The Originator" },
  { id: 96, arabic: "الْبَاقِي", transliteration: "Al-Baqi", meaning: "The Everlasting One" },
  { id: 97, arabic: "الْوَارِثُ", transliteration: "Al-Warith", meaning: "The Inheritor of All" },
  { id: 98, arabic: "الرَّشِيدُ", transliteration: "Ar-Rashid", meaning: "The Righteous Teacher" },
  { id: 99, arabic: "الصَّبُورُ", transliteration: "As-Sabur", meaning: "The Patient One" }
];